foreach(required ANIMA_SOURCE_DIR CONSUMER_BINARY_DIR CONSUMER_MODE CONSUMER_GENERATOR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
if(NOT CONSUMER_CONFIG)
    set(CONSUMER_CONFIG Debug)
endif()
# Only the tiny application's own files are copied. Anima is consumed in place as
# an external source dependency; no engine implementation enters this fixture.
file(MAKE_DIRECTORY "${CONSUMER_BINARY_DIR}/source")
foreach(file CMakeLists.txt main.cpp presentation.hpp replacement.hpp
             camera.hpp lighting.hpp runtime.hpp scene_set.hpp references.hpp lifecycle.hpp audio_output.hpp audio_scene.hpp input.hpp resources.hpp reference.hpp culling.hpp ui.hpp environment.hpp foliage.hpp scene_objects.hpp components.hpp physics.hpp physics2d.hpp navigation.hpp documents.hpp)
    configure_file("${ANIMA_SOURCE_DIR}/tests/consumer/${file}" "${CONSUMER_BINARY_DIR}/source/${file}" COPYONLY)
endforeach()
set(configure_args -S "${CONSUMER_BINARY_DIR}/source" -B "${CONSUMER_BINARY_DIR}/build"
    -G "${CONSUMER_GENERATOR}" "-DANIMA_SOURCE_DIR=${ANIMA_SOURCE_DIR}" "-DCONSUMER_MODE=${CONSUMER_MODE}"
    "-DCMAKE_BUILD_TYPE=${CONSUMER_CONFIG}" -DBUILD_TESTING=ON -DANIMA_WARNINGS_AS_ERRORS=ON)
list(APPEND configure_args "-DANIMA_ENABLE_SANITIZERS=${CONSUMER_SANITIZERS}")
if(NOT "${CONSUMER_MSVC_DEBUG_INFORMATION_FORMAT}" STREQUAL "")
    list(APPEND configure_args "-DCMAKE_MSVC_DEBUG_INFORMATION_FORMAT=${CONSUMER_MSVC_DEBUG_INFORMATION_FORMAT}")
endif()
if(NOT "${CONSUMER_DISABLE_PRECOMPILE_HEADERS}" STREQUAL "")
    list(APPEND configure_args "-DCMAKE_DISABLE_PRECOMPILE_HEADERS=${CONSUMER_DISABLE_PRECOMPILE_HEADERS}")
endif()
if(WIN32 AND CONSUMER_SANITIZERS)
    list(APPEND configure_args "-DCMAKE_CONFIGURATION_TYPES=${CONSUMER_CONFIG}")
endif()
if(CONSUMER_TOOLCHAIN)
    list(APPEND configure_args "-DCMAKE_TOOLCHAIN_FILE=${CONSUMER_TOOLCHAIN}")
endif()
if(CONSUMER_TRIPLET)
    list(APPEND configure_args "-DVCPKG_TARGET_TRIPLET=${CONSUMER_TRIPLET}")
endif()
if(CONSUMER_PLATFORM)
    list(APPEND configure_args -A "${CONSUMER_PLATFORM}")
endif()
if(CONSUMER_TOOLSET)
    list(APPEND configure_args -T "${CONSUMER_TOOLSET}")
endif()
if(CONSUMER_CXX_COMPILER)
    list(APPEND configure_args "-DCMAKE_CXX_COMPILER=${CONSUMER_CXX_COMPILER}")
endif()
if(CONSUMER_C_COMPILER)
    list(APPEND configure_args "-DCMAKE_C_COMPILER=${CONSUMER_C_COMPILER}")
endif()
if(CONSUMER_PREFIX_PATH)
    string(REPLACE ";" "\\;" escaped_prefix "${CONSUMER_PREFIX_PATH}")
    list(APPEND configure_args "-DCMAKE_PREFIX_PATH=${escaped_prefix}")
endif()
if(CONSUMER_MODE STREQUAL "input_sdl" AND CONSUMER_INPUT_SDL_HEADERS)
    list(APPEND configure_args "-DANIMA_INPUT_SDL_INCLUDE_DIR=${CONSUMER_INPUT_SDL_HEADERS}")
endif()
if(CONSUMER_SDL_DIR AND NOT CONSUMER_SDL_DIR MATCHES "NOTFOUND$")
    list(APPEND configure_args "-DSDL3_DIR=${CONSUMER_SDL_DIR}")
endif()
if(CONSUMER_FETCH_SDL)
    list(APPEND configure_args -DANIMA_FETCH_SDL=ON)
    if(CONSUMER_SDL_SOURCE)
        list(APPEND configure_args "-DFETCHCONTENT_SOURCE_DIR_SDL3=${CONSUMER_SDL_SOURCE}")
    endif()
    foreach(kind STATIC SHARED)
        if(DEFINED CONSUMER_SDL_${kind} AND NOT "${CONSUMER_SDL_${kind}}" STREQUAL "")
            list(APPEND configure_args "-DSDL_${kind}=${CONSUMER_SDL_${kind}}")
        endif()
    endforeach()
endif()
if(CONSUMER_MODE MATCHES "^(ui|ui_documents)$" AND CONSUMER_RMLUI_SOURCE)
    list(APPEND configure_args "-DFETCHCONTENT_SOURCE_DIR_RMLUI=${CONSUMER_RMLUI_SOURCE}")
endif()
if(CONSUMER_MODE MATCHES "^(physics|physics_scene|runtime)$" AND CONSUMER_JOLT_SOURCE)
    list(APPEND configure_args "-DFETCHCONTENT_SOURCE_DIR_JOLT=${CONSUMER_JOLT_SOURCE}")
endif()
if(CONSUMER_MODE MATCHES "^(physics2d|runtime)" AND CONSUMER_BOX2D_SOURCE)
    list(APPEND configure_args "-DFETCHCONTENT_SOURCE_DIR_BOX2D=${CONSUMER_BOX2D_SOURCE}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" ${configure_args} COMMAND_ERROR_IS_FATAL ANY)
set(build_args --build "${CONSUMER_BINARY_DIR}/build" --config "${CONSUMER_CONFIG}")
# Respect the caller's build budget; retain the bounded default for ordinary CTest runs.
if("$ENV{CMAKE_BUILD_PARALLEL_LEVEL}" STREQUAL "")
    list(APPEND build_args --parallel 2)
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" ${build_args} COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${CONSUMER_BINARY_DIR}/build"
    -C "${CONSUMER_CONFIG}" --output-on-failure --no-tests=error COMMAND_ERROR_IS_FATAL ANY)
