# A pure event converter needs SDL headers, but no SDL runtime or Vulkan. An
# application already owning SDL can use this target without a second device loop.
find_path(ANIMA_INPUT_SDL_INCLUDE_DIR SDL3/SDL_events.h REQUIRED)
if(NOT EXISTS "${ANIMA_INPUT_SDL_INCLUDE_DIR}/SDL3/SDL_events.h")
    message(FATAL_ERROR "ANIMA_INPUT_SDL_INCLUDE_DIR must contain SDL3/SDL_events.h")
endif()
add_library(anima_input_sdl STATIC src/input/sdl.cpp)
add_library(anima::input_sdl ALIAS anima_input_sdl)
target_include_directories(anima_input_sdl SYSTEM PRIVATE "${ANIMA_INPUT_SDL_INCLUDE_DIR}")
target_include_directories(anima_input_sdl PUBLIC include)
target_link_libraries(anima_input_sdl PUBLIC anima::core)
anima_target_defaults(anima_input_sdl)
if(ANIMA_BUILD_TESTS)
    add_executable(anima_input_sdl_tests tests/input_sdl_tests.cpp)
    target_include_directories(anima_input_sdl_tests SYSTEM PRIVATE "${ANIMA_INPUT_SDL_INCLUDE_DIR}")
    target_link_libraries(anima_input_sdl_tests PRIVATE anima::input_sdl)
    anima_target_defaults(anima_input_sdl_tests)
    add_test(NAME input_sdl COMMAND anima_input_sdl_tests)
endif()
