# Box2D is configured only for explicitly enabled 2D consumers. C is enabled here
# (and in downstream smoke projects) so core-only applications remain C++ only.
enable_language(C)
include(FetchContent)
function(anima_add_box2d)
    set(BUILD_SHARED_LIBS OFF)
    set(BOX2D_AVX2 OFF)
    set(BOX2D_SANITIZE OFF)
    set(BOX2D_COMPILE_WARNING_AS_ERROR OFF)
    FetchContent_Declare(box2d
        URL https://codeload.github.com/erincatto/box2d/tar.gz/refs/tags/v3.1.1
        URL_HASH SHA256=fb6ef914b50f4312d7d921a600eabc12318bb3c55a0b8c0b90608fa4488ef2e4
        DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
    FetchContent_MakeAvailable(box2d)
    anima_enable_sanitizers(box2d)
    set(anima_box2d_source "${box2d_SOURCE_DIR}" PARENT_SCOPE)
endfunction()
anima_add_box2d()
add_library(anima_physics2d STATIC src/physics2d/world.cpp)
add_library(anima::physics2d ALIAS anima_physics2d)
target_include_directories(anima_physics2d PUBLIC include)
target_include_directories(anima_physics2d SYSTEM PRIVATE "${anima_box2d_source}/include")
target_link_libraries(anima_physics2d PRIVATE box2d::box2d)
anima_target_defaults(anima_physics2d)
if(ANIMA_BUILD_ASSETS)
    add_library(anima_physics2d_scene STATIC src/physics2d/scene.cpp)
    add_library(anima::physics2d_scene ALIAS anima_physics2d_scene)
    target_include_directories(anima_physics2d_scene PUBLIC include)
    target_include_directories(anima_physics2d_scene SYSTEM PRIVATE third_party)
    target_link_libraries(anima_physics2d_scene PUBLIC anima::physics2d anima::assets)
    anima_target_defaults(anima_physics2d_scene)
endif()
if(ANIMA_BUILD_TESTS)
    add_executable(anima_physics2d_tests tests/physics2d_tests.cpp)
    target_link_libraries(anima_physics2d_tests PRIVATE anima::physics2d)
    anima_target_defaults(anima_physics2d_tests)
    add_test(NAME physics2d_world COMMAND anima_physics2d_tests)
    if(ANIMA_BUILD_ASSETS)
        add_executable(anima_physics2d_scene_tests tests/physics2d_scene_tests.cpp)
        target_link_libraries(anima_physics2d_scene_tests PRIVATE anima::physics2d_scene)
        anima_target_defaults(anima_physics2d_scene_tests)
        add_test(NAME physics2d_scene COMMAND anima_physics2d_scene_tests)
    endif()
endif()
